# Generated by Django 5.2.6 on 2025-10-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conquistas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conquista',
            name='nmimagem',
            field=models.ImageField(blank=True, null=True, upload_to='conquistas/'),
        ),
    ]
