# Generated by Django 5.2.6 on 2025-10-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conquistas', '0005_remove_conquista_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conquista',
            name='nmimagem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
