# Generated by Django 5.2.6 on 2025-10-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('idnotificacao', models.AutoField(primary_key=True, serialize=False)),
                ('dsmensagem', models.TextField()),
                ('fltipo', models.CharField(choices=[('info', 'Informação'), ('sucesso', 'Sucesso'), ('aviso', 'Aviso'), ('erro', 'Erro')], default='info', max_length=50)),
                ('dtcriacao', models.DateTimeField(auto_now_add=True)),
                ('flstatus', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notificacoes',
                'ordering': ['-dtcriacao'],
            },
        ),
    ]
