# Generated by Django 5.2.6 on 2025-10-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward: Converter ENUM para VARCHAR
            sql="""
                ALTER TABLE desafios 
                    ALTER COLUMN tipo TYPE VARCHAR(20) USING tipo::text;
            """,
            # Reverse: Recriar ENUM (se necessário fazer rollback)
            reverse_sql="""
                -- Recriar o tipo ENUM se necessário fazer rollback
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_desafio_enum') THEN
                        CREATE TYPE tipo_desafio_enum AS ENUM ('diario', 'semanal', 'mensal', 'unico');
                    END IF;
                END $$;
                
                ALTER TABLE desafios 
                    ALTER COLUMN tipo TYPE tipo_desafio_enum USING tipo::tipo_desafio_enum;
            """
        ),
    ]
