# Generated by Django 5.2.6 on 2025-10-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('idatividade', models.AutoField(primary_key=True, serialize=False)),
                ('nmatividade', models.CharField(max_length=100)),
                ('dsatividade', models.TextField(blank=True)),
                ('dificuldade', models.CharField(choices=[('muito_facil', 'Muito fácil'), ('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('muito_dificil', 'Muito difícil')], max_length=20)),
                ('situacao', models.CharField(choices=[('ativa', 'Ativa'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20)),
                ('recorrencia', models.CharField(choices=[('unica', 'Única'), ('recorrente', 'Recorrente')], max_length=20)),
                ('dtatividade', models.DateTimeField()),
                ('dtatividaderealizada', models.DateTimeField(blank=True, null=True)),
                ('tpestimado', models.IntegerField()),
                ('expatividade', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'atividades',
            },
        ),
        migrations.CreateModel(
            name='AtividadeConcluidas',
            fields=[
                ('idatividade_concluida', models.AutoField(primary_key=True, serialize=False)),
                ('dtconclusao', models.DateTimeField()),
            ],
            options={
                'db_table': 'atividades_concluidas',
            },
        ),
    ]
