# Generated by Django 5.2.6 on 2025-10-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward: Converter ENUMs para VARCHAR
            sql="""
                ALTER TABLE atividades 
                    ALTER COLUMN dificuldade TYPE VARCHAR(20) USING dificuldade::text,
                    ALTER COLUMN situacao TYPE VARCHAR(20) USING situacao::text,
                    ALTER COLUMN recorrencia TYPE VARCHAR(20) USING recorrencia::text;
            """,
            # Reverse: Recriar ENUMs (se necessário fazer rollback)
            reverse_sql="""
                -- Recriar os tipos ENUM se necessário fazer rollback
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'dificuldade_enum') THEN
                        CREATE TYPE dificuldade_enum AS ENUM ('muito_facil', 'facil', 'medio', 'dificil', 'muito_dificil');
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'situacao_atividade_enum') THEN
                        CREATE TYPE situacao_atividade_enum AS ENUM ('ativa', 'realizada', 'cancelada');
                    END IF;
                    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'recorrencia_enum') THEN
                        CREATE TYPE recorrencia_enum AS ENUM ('unica', 'recorrente');
                    END IF;
                END $$;
                
                ALTER TABLE atividades 
                    ALTER COLUMN dificuldade TYPE dificuldade_enum USING dificuldade::dificuldade_enum,
                    ALTER COLUMN situacao TYPE situacao_atividade_enum USING situacao::situacao_atividade_enum,
                    ALTER COLUMN recorrencia TYPE recorrencia_enum USING recorrencia::recorrencia_enum;
            """
        ),
    ]
