# Generated by Django 5.2.6 on 2025-10-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0003_remove_enum_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='peso',
            field=models.SmallIntegerField(default=1),
        ),
    ]
