# Generated by Django 5.2.6 on 2025-10-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividades', '0004_atividade_peso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='peso',
        ),
    ]
