# Generated by Django 5.2.6 on 2025-10-03 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nmusuario', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=128)),
                ('emailusuario', models.EmailField(max_length=254, unique=True)),
                ('flsituacao', models.BooleanField(default=True)),
                ('nivelusuario', models.IntegerField(default=1)),
                ('expusuario', models.SmallIntegerField(default=0)),
                ('tipousuario', models.CharField(choices=[('admin', 'Administrador'), ('comum', 'Comum')], default='comum', max_length=10)),
                ('ultima_atividade', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagem_perfil', models.CharField(choices=[('avatar1.png', 'Avatar 1'), ('avatar2.png', 'Avatar 2'), ('avatar3.png', 'Avatar 3'), ('avatar4.png', 'Avatar 4')], default='avatar1.png', max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
