# Generated by Django 5.2.6 on 2025-10-22 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_google_id'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward: Converter ENUM para VARCHAR
            sql="""
                ALTER TABLE usuarios 
                    ALTER COLUMN tipousuario TYPE VARCHAR(20) USING tipousuario::text;
                
                ALTER TABLE usuarios 
                    ALTER COLUMN tipousuario SET DEFAULT 'comum';
            """,
            # Reverse: Recriar ENUM (se necessário fazer rollback)
            reverse_sql="""
                -- Recriar o tipo ENUM se necessário fazer rollback
                DO $$ 
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'tipo_usuario_enum') THEN
                        CREATE TYPE tipo_usuario_enum AS ENUM ('comum', 'admin');
                    END IF;
                END $$;
                
                ALTER TABLE usuarios 
                    ALTER COLUMN tipousuario TYPE tipo_usuario_enum USING tipousuario::tipo_usuario_enum;
            """
        ),
    ]
